In [1]:
import numpy as np


In [3]:
arr = np.arange(1,10)

In [4]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr - 200

array([-199, -198, -197, -196, -195, -194, -193, -192, -191])

In [7]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
arr / 0

/tmp/ipykernel_102644/3942562399.py:1: RuntimeWarning: divide by zero encountered in divide
  arr / 0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [9]:
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [10]:
arr ** arr

array([        1,         4,        27,       256,      3125,     46656,
          823543,  16777216, 387420489])

In [11]:
arr ** 2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])