In [1]:
import numpy as np

In [6]:
arr = np.arange(0,11)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[:5]

array([0, 1, 2, 3, 4])

In [12]:
arr2d=np.array([[1,2,3],[4,5,6]])

In [15]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [18]:
arrr=np.arange(1,11)

In [19]:
arrr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arrr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [21]:
arrr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arrr[arrr > 6]

array([ 7,  8,  9, 10])

In [23]:
arr_2d = np.arange(50).reshape(5,10)

In [30]:
arr_2d[1:3,2:4]

array([[12, 13],
       [22, 23]])

In [ ]:
arr