In [1]:
import numpy as np


In [2]:
arr= np.array([1,2,4])

In [3]:
arr

array([1, 2, 4])

In [4]:
my_mat=[[1,2,3],[4,5,6]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.linspace(0,4,10)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [8]:
np.random.rand(2)

array([0.3146492 , 0.59208009])

In [12]:
np.random.randint(1,100,10)

array([52, 70, 46,  2, 44, 35, 26, 24, 78, 11])